config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'recipes#index'

  get 'pages/about'

  



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :ingredients, dependent: :destroy
	accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true


	has_many :steps, dependent: :destroy
	accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true


	mount_uploader :image, ImageUploader
	
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end

	def privacy
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:remove_image, :image, :title, :description, ingredients_attributes:[:id, :content, :_destroy], steps_attributes:[:id, :direction, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeDb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<nav class="navbar navbar-toggleable-md navbar-light bg-faded"> 

  <%= link_to "Cocina Con Amor", root_path, class: 'navbar-brand' %>

 

    <ul class="navbar-nav navbar-right">

      <li><%= link_to "About", pages_about_path %></li>

      <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

    </ul>

</nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

  <body>
    <%= yield %>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page </h1>


<p>

	
	Welcome to Cocina Con Amor! We specialize in creating authentic Mexican recipes that are sure to leave your mouth watering. Whether it be spicy or not, the recipes will always be fresh, nostalgic, and most of all delicious!
</p>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group">

    <%= form.file_field :image %>

    <% if @recipe.image? %>

      <%= image_tag @recipe.image.url, class: "recipe-show" %>

      <%= form.check_box :remove_image %>

        Remove Image

    <% end %>

 </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-control"%>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

<h3>Add Ingredients</h3>
<%= form.fields_for :ingredients do |ingredient| %>
<%= render 'ingredient_fields', f: ingredient %>
<% end %>
<div class="links">
<%= link_to_add_association 'Add Ingredient', form, :ingredients %>
</div>

<h3>Add Steps</h3>
<%= form.fields_for :steps do |step| %>
<%= render 'step_fields', f: step %>
<% end %>
<div class="links">
<%= link_to_add_association 'Add Step', form, :steps %>
</div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
<div class="field">
<%= f.label :content %>

<%= f.text_field :content %>

<%= link_to_remove_association "remove ingredient", f %>
</div>
</div>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <h2>
    <%= recipe.title %>
  </h2>

  <p>
    <%= recipe.description %>
  </p>

</div>

app/views/recipes/_step_fields.html.erb
<div class="nested-fields">
<div class="field">
<%= f.label :direction %>

<%= f.text_field :direction %>

<%= link_to_remove_association "remove step", f %>
</div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>


<div id="recipes" class="container">
  <h2>Recipes</h2>
  <%= link_to "New Recipe", new_recipe_path, :class => "btn btn-primary" %>
  <div class="row pt-5">
  <% @recipes.each do |recipe| %>
    <div class="col-md-3">
      <div class="recipe-card mb-4">
         <%= image_tag recipe.image.url, class: "recipe-index" if recipe.image? %>

          <%= render recipe %>
          <p>
            <%= link_to "View Recipe", recipe, :class => "btn btn-secondary" %>
          </p>
      </div><!-- recipe-card-->
      </div><!-- col-md-3-->
  <% end %>
</div><!-- row-->
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<% if @recipe.image? %>
  <div class="show-hero">
    <%= image_tag @recipe.image.url, class: "recipe-show" %>
    <div class="show-hero-overlay">
      <%= render @recipe %>
    </div><!-- show-hero-overlay-->
</div><!--- show-hero-->
<% end %>


<div class="container pt-5">
  <h3>Ingredients</h3>
  <ul>
    <% for @ingredient in @recipe.ingredients %>
      <li><%= @ingredient.content %></li>
    <% end %>
  </ul>

  <h3>Steps</h3>
  <ol>
    <% for @step in @recipe.steps %>
      <li><%= @step.direction %></li>
    <% end %>
  </ol>

  <div>
    <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
    <%= link_to "Back to recipes", recipes_path %>

    <%= button_to "Destroy this recipe", @recipe, method: :delete %>
  </div>
</div><!-- container-->